- name: Copy pull secrets
  copy:
    dest: "{{dev_scripts_path}}/pull_secret.json"
    src: pull-secrets.json

- name: Get username
  command: whoami
  changed_when: false
  become: no
  register: whoami

- name: Configure dev-scripts
  copy:
    dest: "{{dev_scripts_path}}/config_{{whoami.stdout}}.sh"
    src: "{{config_file[method]}}"
  register: dev_scripts_config
